"""Seed data for AI Optimization rule definitions."""

RULE_DEFINITION_SEED_DATA = [
    {
        "id": "AIO-ENT-001",
        "title": "Authority sameAs profiles for Organization",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Organization schema should reference authoritative profiles like Wikipedia, Wikidata, or LinkedIn via sameAs to strengthen entity alignment.",
        "why": "Authoritative sameAs links help AI systems connect the brand to trusted knowledge graphs.",
        "fix": "Add sameAs URLs for Wikipedia, Wikidata, and LinkedIn profiles to the Organization JSON-LD block.",
        "confidence": 0.8,
        "acceptance_criteria": "Organization sameAs array includes at least one URL from wikipedia.org, wikidata.org, or linkedin.com.",
    },
    {
        "id": "AIO-ENT-002",
        "title": "Author schema links to expert profile",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Authors should include name, URL, and @id pointing to a detailed expert profile.",
        "why": "Robust author entities reinforce expertise and experience signals for AI rankers.",
        "fix": "Populate author objects with name, canonical profile URL, and a persistent @id.",
        "confidence": 0.7,
        "acceptance_criteria": "Author schema entries include a name and either a URL or @id pointing to an expert profile.",
    },
    {
        "id": "AIO-ENTITY-006",
        "title": "Internal anchors to entity hubs",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Pages should link internally to entity hub pages using descriptive anchor text.",
        "why": "Optimized internal anchors help AI crawlers follow entity relationships across the site.",
        "fix": "Add internal links with descriptive anchor text to the About, Team, or Product entity hubs.",
        "confidence": 0.65,
        "acceptance_criteria": "At least three internal links use descriptive (multi-word) anchor text pointing to entity hub pages.",
    },
    {
        "id": "AIO-ENT-011",
        "title": "Consistent @id for recurring entities",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "When the same entity appears in multiple schema blocks it should reuse the same @id value.",
        "why": "Stable identifiers prevent AI knowledge graphs from fragmenting entity representations.",
        "fix": "Audit schema entries and ensure each recurring entity reuses a single canonical @id.",
        "confidence": 0.85,
        "acceptance_criteria": "Entities sharing the same name reuse a single @id across JSON-LD blocks.",
    },
    {
        "id": "AIO-ENT-012",
        "title": "@id and URL populated on schema nodes",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Every JSON-LD entity should declare both @id and url fields for unambiguous referencing.",
        "why": "Complete identifiers ensure AI agents can dereference entities and crawl canonical pages.",
        "fix": "Add @id and url values to each top-level JSON-LD node, using canonical URLs.",
        "confidence": 0.8,
        "acceptance_criteria": "At least 80% of JSON-LD nodes include both an @id and url field.",
    },
    {
        "id": "AIO-ENT-013",
        "title": "Person schema lists expertise or employer",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Person schema should include knowsAbout or worksFor to qualify expertise.",
        "why": "Explicit topical expertise reinforces E-E-A-T for AI systems.",
        "fix": "Populate knowsAbout topics or worksFor organization on each Person JSON-LD entity.",
        "confidence": 0.75,
        "acceptance_criteria": "At least one Person entity contains knowsAbout or worksFor entries.",
    },
    {
        "id": "AIO-ENT-014",
        "title": "Organization contact or investment profiles",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Organizations should expose ContactPoint data or sameAs links to LinkedIn/Crunchbase.",
        "why": "Reliable contact and investment signals help AI assess legitimacy and scale.",
        "fix": "Add a ContactPoint block or sameAs links for LinkedIn and Crunchbase profiles.",
        "confidence": 0.8,
        "acceptance_criteria": "Organization schema contains a ContactPoint entry or sameAs links referencing linkedin.com or crunchbase.com.",
    },
    {
        "id": "AIO-ENT-015",
        "title": "Wikidata or Wikipedia sameAs linkage",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Entity sameAs arrays should include an authoritative Wikidata or Wikipedia reference.",
        "why": "Knowledge graph alignment accelerates citation and summarization in AI assistants.",
        "fix": "Append the official Wikidata or Wikipedia URL to the sameAs list for the primary entity.",
        "confidence": 0.9,
        "acceptance_criteria": "sameAs contains a URL from wikidata.org or wikipedia.org.",
    },
    {
        "id": "AIO-ENT-016",
        "title": "Founder relationship between Person and Organization",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Organization schema should reference founders via founder linking to Person entities.",
        "why": "Explicit founder relationships tie leadership authority to the brand.",
        "fix": "Add founder references that point to fully populated Person JSON-LD nodes.",
        "confidence": 0.75,
        "acceptance_criteria": "Organization JSON-LD includes a founder property pointing to a Person entity.",
    },
    {
        "id": "AIO-ENT-017",
        "title": "Brand attribution on Product or Service schema",
        "category": "Entity Linking & Brand Consistency",
        "pack": "aio",
        "description": "Products and services should declare a brand property referencing the Organization.",
        "why": "Brand attribution lets AI assistants trace offerings back to the company.",
        "fix": "Populate brand on Product or Service schema, ideally referencing the Organization @id.",
        "confidence": 0.8,
        "acceptance_criteria": "Product or Service JSON-LD nodes include a brand value referencing the organization.",
    },
    {
        "id": "AIO-SCHEMA-003",
        "title": "Use specific schema types",
        "category": "Schema/Structured Data",
        "pack": "aio",
        "description": "Webpages should prefer descriptive schema types such as Service or Product instead of generic WebPage.",
        "why": "Specific schema types unlock richer AI answer surfaces and product cards.",
        "fix": "Update JSON-LD to use the most specific applicable Schema.org type for each page.",
        "confidence": 0.75,
        "acceptance_criteria": "Site includes JSON-LD types beyond WebPage for primary content pages.",
    },
    {
        "id": "AIO-SCHEMA-004",
        "title": "Essential schema fields populated",
        "category": "Schema/Structured Data",
        "pack": "aio",
        "description": "Key schema entities should populate at least 80% of essential properties (name, url, sameAs, etc.).",
        "why": "Complete structured data improves alignment with AI knowledge bases.",
        "fix": "Audit each JSON-LD entity and fill required name, url, @id, sameAs, headline, and description fields.",
        "confidence": 0.8,
        "acceptance_criteria": "Major entity types (Organization, Person, Product, Article) have 80%+ essential fields present.",
    },
    {
        "id": "AIO-CONTENT-005",
        "title": "FAQPage schema with questions and answers",
        "category": "Content Structure",
        "pack": "aio",
        "description": "FAQ content should include JSON-LD with Question and acceptedAnswer pairs.",
        "why": "Structured FAQs power conversational answers and featured snippets in AI tools.",
        "fix": "Add FAQPage schema covering each question with a concise acceptedAnswer.",
        "confidence": 0.6,
        "acceptance_criteria": "FAQPage JSON-LD exposes at least one Question with an acceptedAnswer.",
    },
    {
        "id": "AIO-UX-007",
        "title": "Mobile-friendly and performant markup",
        "category": "Performance & UX",
        "pack": "aio",
        "description": "Pages should declare responsive viewport settings and include performance hints like preload or preconnect.",
        "why": "Responsive, fast-loading pages improve AI ranking signals derived from user satisfaction.",
        "fix": "Add a meta viewport tag and performance resource hints (preload/preconnect) for critical assets.",
        "confidence": 0.5,
        "acceptance_criteria": "Pages include a viewport meta tag and at least one preload, preconnect, or dns-prefetch link.",
    },
    {
        "id": "AIO-SOCIAL-008",
        "title": "Open Graph with verified social profiles",
        "category": "Social Presence",
        "pack": "aio",
        "description": "Pages should expose og meta tags and link to verified social profiles via sameAs or anchors.",
        "why": "Rich social metadata boosts credibility in AI answer cards and knowledge panels.",
        "fix": "Ensure og:title, og:type, og:description, and twitter:card meta tags exist alongside verified social sameAs links.",
        "confidence": 0.6,
        "acceptance_criteria": "Required Open Graph/Twitter tags present and social profile URLs (e.g., twitter.com, youtube.com) referenced in sameAs or page links.",
    },
    {
        "id": "AIO-FRESH-009",
        "title": "Recent last updated metadata",
        "category": "Content Freshness",
        "pack": "aio",
        "description": "Content should expose dateModified or similar metadata updated within the last 12 months.",
        "why": "Fresh content is prioritized by AI systems seeking current information.",
        "fix": "Update and publish dateModified/article:modified_time values whenever content is refreshed.",
        "confidence": 0.55,
        "acceptance_criteria": "A dateModified or article:modified_time value falls within the last 365 days.",
    },
    {
        "id": "AIO-MULTI-010",
        "title": "Multimodal accessibility signals",
        "category": "Multimodal Experience",
        "pack": "aio",
        "description": "Images and videos should provide alt text, captions, or transcripts alongside ImageObject/VideoObject schema.",
        "why": "Accessible multimedia is surfaced more readily by AI assistants and search engines.",
        "fix": "Add descriptive alt text, provide caption tracks or transcripts, and include matching schema for multimedia assets.",
        "confidence": 0.7,
        "acceptance_criteria": "80% of images include alt text and multimedia schema (VideoObject/ImageObject) is present with captions or transcript support.",
    },
    {
        "id": "AIO-SEM-018",
        "title": "mainEntity defined for primary topic",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Pages should declare a mainEntity pointing to the central subject of the content.",
        "why": "mainEntity helps AI models summarize and properly attribute information.",
        "fix": "Add mainEntity to WebPage or Article schema referencing the canonical entity @id.",
        "confidence": 0.85,
        "acceptance_criteria": "JSON-LD includes a mainEntity property referencing the core entity.",
    },
    {
        "id": "AIO-SEM-019",
        "title": "about and mentions with entity URIs",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Structured data should list related entities in about or mentions arrays with canonical URIs.",
        "why": "Rich entity relationships teach AI systems how topics interrelate.",
        "fix": "Populate about or mentions arrays with objects that include @id or sameAs URLs.",
        "confidence": 0.8,
        "acceptance_criteria": "about or mentions arrays contain items providing an @id or sameAs URI.",
    },
    {
        "id": "AIO-SEM-020",
        "title": "Specific page-level @type",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Each page should use an appropriate specific @type such as AboutPage, ContactPage, or BlogPosting.",
        "why": "Precise page @types guide AI assistants on intent and audience.",
        "fix": "Update page-level JSON-LD to use AboutPage/ContactPage/BlogPosting or similar specific types.",
        "confidence": 0.75,
        "acceptance_criteria": "Pages adopt a specific page-level @type aligned with their purpose (e.g., AboutPage for /about).",
    },
    {
        "id": "AIO-SEM-021",
        "title": "Article headline and description populated",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Articles and blog posts should include headline and description fields in schema.",
        "why": "Headline and description metadata enable accurate summarization in AI results.",
        "fix": "Populate headline and description on Article or BlogPosting schema entries.",
        "confidence": 0.8,
        "acceptance_criteria": "Article or BlogPosting entities declare both headline and description fields.",
    },
    {
        "id": "AIO-SEM-022",
        "title": "Semantic HTML coverage",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Pages should utilize semantic HTML elements such as article, section, header, and footer for at least 80% of layout sections.",
        "why": "Semantic markup helps AI segment content and extract key answers.",
        "fix": "Wrap primary content in semantic elements (article/section/header/footer) instead of generic divs.",
        "confidence": 0.65,
        "acceptance_criteria": "At least 80% of sampled pages include multiple semantic HTML elements (article/section/header/footer).",
    },
    {
        "id": "AIO-SEM-023",
        "title": "Canonical URL on every indexable page",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "All indexable pages should declare a canonical URL to avoid duplication.",
        "why": "Canonical tags help AI models resolve duplicates and consolidate authority.",
        "fix": 'Add rel="canonical" links to every indexable page, excluding those marked noindex.',
        "confidence": 0.9,
        "acceptance_criteria": "Every indexable page includes a canonical link element.",
    },
    {
        "id": "AIO-SEM-024",
        "title": "Comprehensive social meta tags",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Pages should include og:type, og:title, og:description, and twitter:card meta tags.",
        "why": "Consistent open graph data improves AI snippet rendering and sharing fidelity.",
        "fix": "Ensure required Open Graph and Twitter card meta tags are present and descriptive.",
        "confidence": 0.7,
        "acceptance_criteria": "Meta tags og:type, og:title, og:description, and twitter:card are present on the page.",
    },
    {
        "id": "AIO-SEM-025",
        "title": "BreadcrumbList schema implemented",
        "category": "Semantic/Intent",
        "pack": "aio",
        "description": "Pages should expose BreadcrumbList schema to communicate site hierarchy.",
        "why": "Breadcrumbs help AI agents understand navigation context and improve answer grounding.",
        "fix": "Add BreadcrumbList JSON-LD describing the page's position in the site hierarchy.",
        "confidence": 0.75,
        "acceptance_criteria": "JSON-LD includes a BreadcrumbList entry with at least one item.",
    },
]
