"""
Report generation engine for AI Visibility MVP
Generates Markdown and DOCX audit reports
"""

from datetime import datetime
from io import BytesIO
from typing import Dict, List

from docx import Document
from docx.shared import Pt, RGBColor


def generate_markdown(site_url: str, packs: List[str], scores: Dict, findings: List[Dict]) -> str:
    """
    Generates Markdown format report.

    Args:
        site_url: Audited website URL
        packs: List of pack identifiers used
        scores: Scores dict with overall and by_category
        findings: List of finding dicts

    Returns:
        Markdown string
    """
    current_date = datetime.now().strftime("%Y-%m-%d")

    # Build markdown
    md = f"""# AI Visibility Audit Report

**Site:** {site_url}
**Date:** {current_date}
**Rule Packs:** {', '.join(packs)}
**Tool Version:** v0.1

---

## Summary

**Overall Score:** {scores['overall']:.1f}%

### Scores by Category

"""

    for category, score in scores["by_category"].items():
        md += f"- **{category}:** {score:.1f}%\n"

    md += "\n---\n\n## Findings\n\n"

    # Passed rules
    passed = [f for f in findings if f["status"] == "pass"]
    if passed:
        md += "### Passed Rules ✅\n\n"
        for finding in passed:
            md += f"- **{finding['id']}** - {finding['title']}\n"
        md += "\n"

    # Issues found
    issues = [f for f in findings if f["status"] in ["fail", "partial"]]
    if issues:
        md += "### Issues Found ⚠️\n\n"
        for finding in issues:
            md += f"#### {finding['id']} - {finding['title']}\n\n"
            md += f"**Status:** {finding['status']}  \n"
            md += f"**Category:** {finding['category']}\n\n"
            if finding.get("confidence") is not None:
                md += f"**Confidence:** {finding['confidence'] * 100:.0f}%\n\n"
            md += f"**Why it matters:** {finding['why']}\n\n"

            if finding["evidence"]:
                md += "**Evidence:**\n"
                for evidence in finding["evidence"]:
                    md += f"- URL: {evidence['url']}\n"
                    md += f"  - {evidence['snippet']}\n"
                md += "\n"

            md += f"**How to fix:** {finding['fix']}\n\n"
            md += "---\n\n"

    md += """---

## About This Report

This is a quick scan analyzing up to 12 pages for AI discoverability. For a comprehensive audit covering your entire site, contact us for a Full Audit.

**Generated by:** AI Visibility Audit Tool v0.1
"""

    return md


def generate_docx(site_url: str, packs: List[str], scores: Dict, findings: List[Dict]) -> bytes:
    """
    Generates DOCX format report using python-docx.

    Args:
        site_url: Audited website URL
        packs: List of pack identifiers used
        scores: Scores dict with overall and by_category
        findings: List of finding dicts

    Returns:
        Bytes object containing DOCX file
    """
    current_date = datetime.now().strftime("%Y-%m-%d")

    doc = Document()

    # Title section
    doc.add_heading("AI Visibility Audit Report", 0)
    doc.add_paragraph(f"Site: {site_url}")
    doc.add_paragraph(f"Date: {current_date}")
    doc.add_paragraph(f"Rule Packs: {', '.join(packs)}")
    doc.add_paragraph(f"Tool Version: v0.1")

    # Summary section
    doc.add_heading("Summary", 1)
    doc.add_paragraph(f"Overall Score: {scores['overall']:.1f}%")

    doc.add_heading("Scores by Category", 2)

    # Add table for category scores
    table = doc.add_table(rows=1, cols=2)
    table.style = "Light Grid Accent 1"
    header_cells = table.rows[0].cells
    header_cells[0].text = "Category"
    header_cells[1].text = "Score"

    for category, score in scores["by_category"].items():
        row_cells = table.add_row().cells
        row_cells[0].text = category
        row_cells[1].text = f"{score:.1f}%"

    # Findings section
    doc.add_heading("Findings", 1)

    # Passed rules
    passed = [f for f in findings if f["status"] == "pass"]
    if passed:
        doc.add_heading("Passed Rules", 2)
        for finding in passed:
            doc.add_paragraph(f"✓ {finding['id']} - {finding['title']}", style="List Bullet")

    # Issues found
    issues = [f for f in findings if f["status"] in ["fail", "partial"]]
    if issues:
        doc.add_heading("Issues Found", 2)
        for finding in issues:
            doc.add_heading(f"{finding['id']} - {finding['title']}", 3)
            doc.add_paragraph(f"Status: {finding['status']}")
            doc.add_paragraph(f"Category: {finding['category']}")
            if finding.get("confidence") is not None:
                doc.add_paragraph(f"Confidence: {finding['confidence'] * 100:.0f}%")
            doc.add_paragraph(f"Why it matters: {finding['why']}")

            if finding["evidence"]:
                doc.add_paragraph("Evidence:")
                for evidence in finding["evidence"]:
                    doc.add_paragraph(f"  • URL: {evidence['url']}", style="List Bullet 2")
                    doc.add_paragraph(f"    {evidence['snippet']}", style="List Bullet 3")

            doc.add_paragraph(f"How to fix: {finding['fix']}")

    # Footer
    doc.add_paragraph("_" * 50)
    doc.add_heading("About This Report", 2)
    doc.add_paragraph(
        "This is a quick scan analyzing up to 12 pages for AI discoverability. "
        "For a comprehensive audit covering your entire site, contact us for a Full Audit."
    )
    doc.add_paragraph("Generated by: AI Visibility Audit Tool v0.1")

    # Convert to bytes
    bio = BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio.getvalue()


# ==============================
# Playbook Report Generators
# ==============================


def generate_playbook_markdown(playbook: Dict) -> str:
    """
    Generate Markdown report for a visibility playbook.
    """
    domain = playbook.get("domain", "")
    intent = playbook.get("intent", "")
    fixes = playbook.get("fixes", [])

    md = [
        f"# Visibility Playbook — {domain}",
        f"**Intent:** {intent}",
        "",
        "## TL;DR",
        "```html",
        (playbook.get("tldr_html") or "").strip(),
        "```",
        "",
        "## FAQ",
        "```html",
        (playbook.get("faq_html") or "").strip(),
        "```",
        "",
        "## Organization JSON-LD",
        "```json",
        __import__("json").dumps(playbook.get("jsonld", {}), indent=2),
        "```",
        "",
        "## Fixes",
    ]
    for fix in fixes:
        md.extend(
            [
                f"### {fix.get('title')}",
                f"Why: {fix.get('why', '')}",
                "```" + (fix.get("language") or ""),
                (fix.get("snippet") or "").strip(),
                "```",
                "",
            ]
        )

    md.extend(
        [
            "## Acceptance Tests",
            "```python",
            (playbook.get("acceptance_tests_py") or "").strip(),
            "```",
        ]
    )

    return "\n".join(md)


def generate_playbook_docx(playbook: Dict) -> bytes:
    """
    Generate DOCX document for a visibility playbook.
    """
    domain = playbook.get("domain", "")
    intent = playbook.get("intent", "")
    fixes = playbook.get("fixes", [])

    doc = Document()
    doc.add_heading("Visibility Playbook", 0)
    doc.add_paragraph(f"Domain: {domain}")
    doc.add_paragraph(f"Intent: {intent}")

    # TL;DR
    doc.add_heading("TL;DR", 1)
    doc.add_paragraph(playbook.get("tldr_html") or "")

    # FAQ
    doc.add_heading("FAQ", 1)
    doc.add_paragraph(playbook.get("faq_html") or "")

    # JSON-LD
    doc.add_heading("Organization JSON-LD", 1)
    doc.add_paragraph(__import__("json").dumps(playbook.get("jsonld", {}), indent=2))

    # Fixes
    doc.add_heading("Fixes", 1)
    for fix in fixes:
        doc.add_heading(fix.get("title") or "Fix", 2)
        doc.add_paragraph(f"Why: {fix.get('why', '')}")
        snippet = fix.get("snippet") or ""
        doc.add_paragraph(snippet)

    # Acceptance tests
    doc.add_heading("Acceptance Tests", 1)
    doc.add_paragraph(playbook.get("acceptance_tests_py") or "")

    bio = BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio.getvalue()
